export const commonCopy = {
  apply: "Apply",
  reset: "Reset",
  signIn: "Sign in",
  loading: "Loading...",
  noResults: "No results",
  optional: "Optional",
  comingSoon: "Coming soon",
};

export const navCopy = {
  products: "Products",
  orders: "Orders",
  openShop: "Open a shop",
  sellerCenter: "Seller Center",
  search: "Search",
  notifications: "Notifications",
  cart: "Cart",
  profile: "Profile",
};

export const productCopy = {
  shopFallback: "Shop",
  noReviews: "No reviews yet",
  detailFallback: "This product does not have a detailed description yet.",
  stockLeft: (count: number) => `${count} left`,
  stockItems: (count: number) => `${count} items in stock`,
};

export const searchCopy = {
  placeholder: "Search products, brands, shops, or describe what you need...",
  keyword: "Keyword",
  intent: "Intent AI",
  modeLabel: "Search mode",
  button: "Search",
  overlayTitle: "Find products the way you think.",
  overlaySubtitle: "Try a natural shopping request and we will search the catalog for matching products.",
  suggestions: [
    "laptop for programming under $800",
    "noise-cancelling headphones for online classes",
    "birthday tech gift for her",
    "affordable running shoes for students",
  ],
};

export const authCopy = {
  login: {
    heroTitle: "Sign in to Aeris Market.",
    heroText: "Sign in to shop, track orders, chat with stores, or access your role-based workspace.",
    title: "Welcome back",
    subtitle: "Sign in to shop, track orders, and message stores.",
    password: "Password",
    submitting: "Signing in...",
    submit: "Sign in",
    createAccount: "Create account",
    needHelp: "Need help?",
    error: "Unable to sign in.",
  },
  register: {
    eyebrow: "Create account",
    title: "Create a buyer account",
    subtitle: "After registration, the backend sends an email OTP to activate your account.",
    fullName: "Full name",
    password: "Strong password",
    submitting: "Sending...",
    submit: "Register and send OTP",
    already: "Already have an account?",
    sent: "OTP has been sent to your email. Check MailHog or the configured backend mailbox.",
    error: "Unable to register.",
    existingEmailNeedOtp: "This email already has an account waiting for verification. A new OTP has been sent.",
  },
  verify: {
    eyebrow: "Verify OTP",
    title: "Activate account",
    otp: "Enter OTP",
    submitting: "Verifying...",
    submit: "Verify OTP",
    resend: "Resend OTP",
    resent: "A new OTP has been sent.",
    back: "Back to sign in",
    success: "Your account is active. You can sign in now.",
    error: "Unable to verify OTP.",
  },
};

export const buyerCopy = {
  loginRequiredTitle: "Sign in required",
  loginRequiredText: "Sign in to continue with your account.",
  cart: {
    title: "Cart",
    loading: "Loading your cart...",
    empty: "Your cart is empty.",
    summary: "Order summary",
    subtotal: "Subtotal",
    shipping: "Shipping",
    free: "Free",
    total: "Total",
    checkout: "Checkout",
  },
  orders: {
    title: "My orders",
    loading: "Loading orders...",
    empty: "You do not have any orders yet.",
    detail: "Order tracking",
    summary: "Summary",
    items: "Order items",
    statusTimeline: "Status timeline",
    orderNumber: (id: string | number) => `Order #${id}`,
  },
  notifications: {
    title: "Notifications",
    markAllRead: "Mark all as read",
    empty: "No notifications yet.",
  },
  profile: {
    title: "Profile",
    update: "Update profile",
    save: "Save changes",
  },
};

export const sellerCopy = {
  shell: {
    title: "Seller Center",
    eyebrow: "Shop operations",
    signInTitle: "Seller sign in required",
    signInText: "Sign in with a seller account to manage your shop.",
    links: {
      overview: "Overview",
      shop: "Shop",
      products: "Products",
      orders: "Orders",
      customerChat: "Customer chat",
      chatbot: "Chatbot",
      analytics: "Analytics",
    },
  },
  common: {
    loading: "Loading seller workspace...",
    save: "Save changes",
    saving: "Saving...",
    empty: "No records found.",
    error: "Unable to load seller data.",
    success: "Changes saved.",
    addProduct: "Add product",
    edit: "Edit",
    delete: "Delete",
  },
  dashboard: {
    revenue: "Revenue",
    orders: "Orders",
    products: "Products",
    pendingOrders: "Orders to process",
    noPendingOrders: "No pending orders right now.",
    chatbotTitle: "Shop chatbot",
    chatbotText: "Configure AI connection, response guidance, templates, and availability.",
    configure: "Configure",
    transitionHint: "Pending → Processing",
  },
  products: {
    eyebrow: "Product catalog",
    title: "Shop products",
    name: "Product name",
    description: "Description",
    price: "Price",
    stock: "Stock",
    categoryId: "Category ID",
    category: "Category",
    createTitle: "Create product",
    editTitle: "Edit product",
    createSubmit: "Create product",
    updateSubmit: "Save product",
    creating: "Creating...",
    updating: "Saving...",
    empty: "Your shop has no products yet.",
    notFound: "Product not found.",
    created: "Product created.",
    updated: "Product updated.",
    deleted: "Product deleted.",
  },
  orders: {
    eyebrow: "Order management",
    title: "Seller orders",
    detailTitle: (id: string | number) => `Order #${id}`,
    empty: "No orders for this shop yet.",
    buyer: "Buyer",
    items: "Items",
    total: "Total",
    payment: "Payment",
    shipping: "Shipping",
    shippingAddress: "Shipping address",
    shippingNote: "Shipping note",
    updateStatus: "Update order status",
    updateShipping: "Update shipping",
    statuses: {
      pending: "Pending",
      processing: "Processing",
      shipping: "Shipping",
      delivered: "Delivered",
      cancelled: "Cancelled",
    } as Record<string, string>,
    shippingStatuses: {
      preparing: "Preparing",
      shipped: "Shipped",
      delivered: "Delivered",
      delayed: "Delayed",
    } as Record<string, string>,
  },
  shop: {
    eyebrow: "Shop profile",
    title: "Shop settings",
    name: "Shop name",
    description: "Shop description",
    status: "Status",
    missing: "Create your shop profile to start selling.",
  },
  stats: {
    eyebrow: "Analytics",
    title: "Shop performance",
    revenue: "Revenue",
    orders: "Orders",
    bestSelling: "Best-selling products",
    sold: (count: number) => `${count} sold`,
  },
  chatbot: {
    eyebrow: "Automation",
    title: "Shop chatbot",
    enabled: "Enable chatbot",
    apiKey: "AI service key",
    prompt: "Response guidance",
    template: "Answer template",
    securityNote: "Secrets are stored by the backend and may be returned masked after saving.",
  },
  request: {
    eyebrow: "Seller onboarding",
    title: "Open a shop",
    subtitle: "Submit your shop profile for admin review.",
    shopName: "Shop name",
    description: "Shop description",
    submit: "Submit request",
    submitting: "Submitting...",
    success: "Seller request submitted for review.",
    signInText: "Sign in before submitting a seller request.",
  },
};

export const labelFromMap = (labels: Record<string, string>, value?: string | null) => value ? labels[value] ?? value : "—";
