export const adminCopy = {
  common: {
    loading: "Loading...",
    empty: "No records found.",
    error: "Unable to load data.",
    signInRequired: "Sign in as an admin to view live data.",
    refresh: "Refresh",
    save: "Save changes",
    saving: "Saving...",
    search: "Search users, reports, or logs...",
  },
  shell: {
    brand: "Aeris Admin",
    subtitle: "Control plane",
    workspace: "Administrator workspace",
    description: "Manage system operations, moderation, and access control.",
    adminOnly: "Admin-only area",
    adminOnlyText: "Restricted workspace for operations, moderation, and role management.",
    login: "Admin login",
    systemNominal: "System nominal",
    links: {
      overview: "Overview",
      users: "Users & roles",
      sellerRequests: "Seller onboarding",
      reports: "Reports & moderation",
      auditTrail: "Audit trail",
      metrics: "Metrics",
      logs: "System logs",
    },
  },
  login: {
    title: "Admin sign in",
    subtitle: "Access the operations console with an administrator account.",
    email: "Admin email",
    password: "Password",
    submit: "Sign in",
    submitting: "Signing in...",
    error: "Unable to sign in.",
  },
  dashboard: {
    eyebrow: "Overview",
    title: "Operations dashboard",
    description: "Monitor marketplace health, moderation queues, and system activity from backend data.",
    users: "Users",
    products: "Products",
    orders: "Orders",
    revenue: "Revenue",
    shops: "Shops",
    pendingSellerRequests: "Pending seller requests",
    pendingReports: "Pending reports",
    recentLogs: "Recent system logs",
  },
  users: {
    eyebrow: "Access control",
    title: "Users & roles",
    description: "Review user accounts, status, and marketplace roles.",
    search: "Search email or role...",
    allRoles: "All roles",
    allStatuses: "All statuses",
    user: "User",
    role: "Role",
    status: "Status",
    actions: "Actions",
    activate: "Activate",
    ban: "Ban",
    changeRole: "Change role",
    detail: "Review details",
    noMatch: "No users match the current filters.",
  },
  sellerRequests: {
    eyebrow: "Seller onboarding",
    title: "Seller requests",
    description: "Review shop applications and approve or reject seller onboarding requests.",
    search: "Search shop or user ID...",
    allStatuses: "All statuses",
    reason: "Review note",
    reasonPlaceholder: "Reason for approval or rejection",
    approve: "Approve",
    reject: "Reject",
    criteria: "Approval criteria",
    empty: "No seller requests match the current filters.",
  },
  reports: {
    eyebrow: "Moderation",
    title: "Reports & moderation",
    description: "Review marketplace reports and update moderation status.",
    signIn: "Sign in as an admin to view reports.",
    resolve: "Resolve",
    pendingQueue: "Pending queue",
    pendingReports: "pending reports",
    auditLink: "Open audit trail",
    empty: "No reports found.",
  },
  metrics: {
    eyebrow: "System analytics",
    title: "Metrics",
    description: "Aggregate backend metrics for marketplace activity and operations.",
    signIn: "Sign in as an admin to view metrics.",
    users: "Users",
    shops: "Shops",
    orders: "Orders",
    revenue: "Revenue",
    products: "Products",
    payments: "Payments",
  },
  logs: {
    eyebrow: "Operations",
    title: "System logs",
    description: "Inspect recent system events collected by the backend admin service.",
    auditTitle: "Audit logs",
    auditDescription: "Review administrative actions recorded by the backend.",
    signIn: "Sign in as an admin to view logs.",
    empty: "No logs found.",
  },
  statuses: {
    active: "Active",
    banned: "Banned",
    pending_verification: "Pending verification",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    resolved: "Resolved",
    normal: "Normal",
    warning: "Warning",
    ERROR: "Error",
  } as Record<string, string>,
  roles: {
    buyer: "Buyer",
    seller: "Seller",
    admin: "Admin",
  } as Record<string, string>,
};

export const labelFromMap = (labels: Record<string, string>, value?: string | null) => value ? labels[value] ?? value : "—";
